lib/forum_web/router.ex
defmodule ForumWeb.Router do
  use ForumWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ForumWeb do
    pipe_through :browser

    get "/", ThreadController, :index
    get "/thread/new", ThreadController, :new

    resources "/thread", ThreadController, only: [:show, :create, :delete] do
      resources "/", CommentController, only: [:create, :delete]
    end
  end

  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ForumWeb.Telemetry
    end
  end
end

lib/forum/thread.ex
defmodule Forum.Thread do
  use Ecto.Schema
  import Ecto.Changeset

  alias Forum.Comment

  schema "thread" do
    field :username, :string
    field :title, :string
    field :description, :string
    has_many(:comments, Comment, foreign_key: :thread_id)
    timestamps()
  end

  def build(params) do
    params
    |> changeset()
    |> apply_action(:insert)
  end

  @required_params [:username, :title, :description]
  def changeset(params), do: create_changeset(%__MODULE__{}, params)
  def changeset(thread, params), do: create_changeset(thread, params)

  defp create_changeset(thread_or_module, params) do
    thread_or_module
    |> cast(params, @required_params)
    |> validate_required(@required_params)
    |> validate_length(:title, min: 3, max: 255)
    |> validate_length(:description, min: 3)
    |> validate_length(:username, min: 3, max: 255)
  end
end

lib/forum/thread/comment/index.ex
defmodule Forum.Thread.Comment.Index do
  import Ecto.Query
  alias Forum.{Repo, Comment}

  def call(thread_id, page \\ 1) do
    Comment
    |> where(thread_id: ^thread_id)
    |> order_by(desc: :inserted_at)
    |> Repo.paginate(page: page)
  end
end

lib/forum/thread/create.ex
defmodule Forum.Thread.Create do
  alias Forum.{Repo, Thread}

  def call(params) do
    params
    |> Thread.build()
    |> create_thread()
  end

  defp create_thread({:error, _struct} = error), do: error
  defp create_thread({:ok, struct}), do: Repo.insert(struct)
end

lib/forum/thread/delete.ex
defmodule Forum.Thread.Delete do
  alias Forum.{Repo}

  def call(id) do
    case Forum.fetch_thread(id) do
      {:error, message} -> {:error, message}
      {:ok, thread} -> Repo.delete(thread)
    end
  end
end

lib/forum/thread/fetch.ex
defmodule Forum.Thread.Fetch do
  alias Forum.{Thread, Repo}

  def call(id) do
    case Integer.parse(id) do
      {id, ""} -> get(id)
      _ -> {:error, "Invalid thread id format"}
    end
  end

  def get(id) do
    case Repo.get(Thread, id) do
      nil -> {:error, "Thread ##{id} not found!"}
      thread -> {:ok, thread}
    end
  end
end

lib/forum/thread/index.ex
defmodule Forum.Thread.Index do
  import Ecto.Query
  alias Forum.{Repo, Thread}

  def call(options \\ []) do
    count_comments = Keyword.get(options, :count_comments, false)
    page = Keyword.get(options, :page, 1)

    result =
      Thread
      |> order_by(desc: :inserted_at)
      |> Repo.paginate(page: page)

    if count_comments,
      do: Map.merge(result, %{entries: with_comments_count(result.entries)}),
      else: result
  end

  def with_comments_count(threads), do: Enum.map(threads, fn t -> count_comments(t) end)

  defp count_comments(thread) do
    query = from comment in "comment", where: comment.thread_id == ^thread.id
    count = Repo.aggregate(query, :count, :id)
    thread |> Map.put(:comments_count, count)
  end
end

lib/forum_web/controllers/thread_controller.ex
defmodule ForumWeb.ThreadController do
  use ForumWeb, :controller
  alias Forum.{Thread, Comment}
  alias ForumWeb.ControllersHelpers

  def new(conn, _params) do
    changeset = Thread.changeset(%Thread{}, %{})

    conn
    |> render("new.html",
      changeset: changeset
    )
  end

  def index(conn, params) do
    {page, ""} =
      Map.get(params, "page", "1")
      |> Integer.parse()

    result = Forum.get_threads(count_comments: true, page: page)

    render(conn, "index.html",
      threads: result.entries,
      total_pages: result.total_pages,
      current_page: result.page_number
    )
  end

  def create(conn, %{"thread" => thread}) do
    case Forum.create_thread(thread) do
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)

      {:ok, thread} ->
        redirect(conn, to: Routes.thread_path(conn, :show, thread.id))
    end
  end

  def show(conn, params) do
    changeset = Comment.changeset(%{})

    %{"id" => thread_id} = params

    {page, ""} =
      Map.get(params, "page", "1")
      |> Integer.parse()

    case Forum.fetch_thread(thread_id) do
      {:ok, thread} ->
        ControllersHelpers.handle_show_thread(conn, thread, changeset, page)

      {:error, message} ->
        redirect_flash_index(conn, message, :error)
    end
  end

  def delete(conn, %{"id" => thread_id}) do
    case Forum.delete_thread(thread_id) do
      {:ok, _thread} -> redirect_flash_index(conn, "The thread ##{thread_id} has been deleted")
      {:error, message} -> redirect_flash_index(conn, message, :error)
    end
  end

  defp redirect_flash_index(conn, message, flash_type \\ :info, path \\ :index),
    do: ControllersHelpers.redirect_flash(conn, flash_type, message, path, [])
end

lib/forum_web/views/thread_view.ex
defmodule ForumWeb.ThreadView do
  use ForumWeb, :view

  def custom_error_tag(form, field) do
    Enum.map(Keyword.get_values(form.errors, field), fn error ->
      content_tag(:span, translate_error(error),
        class:
          "bg-red-100 rounded-md text-red-800 border-2 border-red-300 mt-2 w-1/2 text-center p-1",
        phx_feedback_for: input_name(form, field)
      )
    end)
  end

  def show_with_page(conn, page, thread) do
    Routes.thread_path(conn, :show, thread.id, page: page)
  end
end

lib/forum_web/templates/thread/index.html.eex
<section class="flex justify-between w-full mt-4">
    <h2 class="text-4xl font-bold"> Threads </h2>
    <%= link "New Thread", to: Routes.thread_path(@conn, :new), class: "bg-gray-300 hover:bg-gray-400 border-2 border-black rounded-md w-32 text-center pt-1 text-lg" %>
</section>


<%= if length(@threads) > 0 do%>
    <ul class="mt-8">
        <%= for thread <- @threads do %>
            <li class="group border-b-2 border-black py-4">
                <div class="flex justify-between">
                    <span class="text-2xl font-medium break-words"> <%= thread.title %> </span>
                    <div class="flex">
                        <span class="font-bold w-20 text-right"> <%= thread.comments_count %> replies </span>
                        <%= link "details", to: Routes.thread_path(@conn, :show, thread.id), class: "text-blue-500 hover:text-blue-600 hover:underline font-bold px-2"%>
                    </div>
                </div>
                <p class="text-xs font-medium"> <%= thread.inserted_at %> (UTC)</p>
            </li>
        <% end %>
    </ul>
    <%= if @total_pages > 0 do %>
        <footer class="mt-8 flex justify-center text-center text-lg">

            <%= if @current_page > 1, do: link "<", to: Routes.thread_path(@conn, :index, page: @current_page-1) %>
            <%= for page <- Enum.to_list(1..@total_pages) do %>
                <%= if page == @current_page do %>
                    <span class="px-1 font-bold"> <%= page %> </span>
                <% else %>
                    <%= link page, to: Routes.thread_path(@conn, :index, page: page), class: "px-1" %>
                <% end %>
            <% end %>
            <%= if @current_page < @total_pages, do: link ">", to: Routes.thread_path(@conn, :index, page: @current_page+1) %>
        </footer>
    <% end %>
<% else %>
    <span class="text-center text-lg mt-12"> No threads have been created yet, create one by clicking on <span class="font-bold"> "new thread" </span> </span>
<% end %>

lib/forum_web/templates/thread/new.html.eex
<h2 class="text-4xl font-bold"> New Thread </h2>

<%= form_for @changeset, ForumWeb.Router.Helpers.thread_path(@conn, :create), [class: "mt-4 flex flex-col", style: "width: 40rem"], fn f -> %>

    <p class="flex flex-col my-2 w-1/2">
        <%= text_input f, :title, placeholder: "Title", class: "border-2 border-gray-700 rounded p-1" %>
            <%= custom_error_tag f, :title %>
    </p>
    <p class="flex flex-col my-2">
        <%= textarea f, :description, placeholder: "Description", class: "border-2 border-gray-700 rounded p-1 h-48" %>
        <%= custom_error_tag f, :description %>
    </p>
    <div class="flex flex-row w-full my-2">
        <p class="flex flex-col w-1/2">
            <%= text_input f, :username, placeholder: "Your name", class: "border-2 border-gray-700 rounded p-1" %>
            <%= custom_error_tag f, :username %>
        </p>
        <div class="w-full flex justify-end">
            <%= submit "Save Thread", class: "bg-green-200 hover:bg-green-300 border-2 border-black rounded-md w-32 mx-2 mb-4 mt-0 h-8" %>
            <%= link "Cancel", to: Routes.thread_path(@conn, :index), class: "bg-gray-300 hover:bg-gray-400 border-2 border-black rounded-md w-24 ml-2 mb-4 mt-0 h-8 text-center pt-0.5", method: :get %>
        </div>
    </div>

<% end %>

lib/forum_web/templates/thread/show.html.eex
<div>
    <div class="flex font-medium items-top justify-between">
        <p class="w-4/5 text-4xl pr-4">
            <%= @thread.title %> #<%= @thread.id %> <span class="text-lg"> - <%= @thread.username %> </span>
        </p>
        <%= link "Delete thread", to: Routes.thread_path(@conn, :delete, @thread.id), class: "bg-red-400 hover:bg-red-500 border-2 border-black rounded-md px-1 text-center pt-0.5 h-8 w-1/5", method: :delete%>
    </div>
    <p class="text-xs font-medium"> <%= @thread.inserted_at %> (UTC)</p>
    <p class="text-gray-600 text-justify font-medium my-4 break-words">
        <%= @thread.description %>
    </p>
</div>

<hr class="border bg-black border-gray-400" />

<%= if length(@comments) > 0 do %>
    <section class="mt-6 mb-4">
        <h3 class="text-3xl font-bold"> Replies </h3>
        <ul>
            <%= for comment <- @comments do %>
                <li class="flex justify-between py-2 hover:bg-gray-200 pl-2 rounded-md group">
                    <div class="flex flex-col w-5/6">
                        <p class="font-medium"> <%= comment.username %>: </p>
                        <p class="text-gray-500 font-medium text-justify break-words"> <%= comment.message %> </p>
                        <p class="text-xs font-medium"> <%= comment.inserted_at %> (UTC)</p>
                    </div>
                    <%= link "Delete comment", to: Routes.thread_comment_path(@conn, :delete, @thread.id, comment.id), class: "bg-red-400 hover:bg-red-500 border-2 border-black rounded-md px-1 text-center text-sm pt-1 h-8 w-1/6 mx-2 opacity-0 group-hover:opacity-100", method: :delete%>
                </li>
            <% end %>
        </ul>
            <%= if @total_pages > 0 do %>
        <footer class="mt-8 flex justify-center text-center text-lg">

            <%= if @current_page > 1, do: link "<", to: show_with_page(@conn, @current_page-1, @thread) %>
            <%= for page <- Enum.to_list(1..@total_pages) do %>
                <%= if page == @current_page do %>
                    <span class="px-1 font-bold"> <%= page %> </span>
                <% else %>
                    <%= link page, to: show_with_page(@conn, page, @thread), class: "px-1" %>
                <% end %>
            <% end %>
            <%= if @current_page < @total_pages, do: link ">", to: show_with_page(@conn, @current_page+1, @thread) %>
        </footer>
    <% end %>
    </section>


<% else %>
    <span class="text-center text-lg my-12"> No replies yet, create one below </span>
<% end %>


<section>
    <h3 class="text-2xl font-bold mb-2"> Reply: </h3>
    <%= form_for @changeset, Routes.thread_comment_path(@conn, :create, @thread_id), fn f -> %>

        <p class="flex flex-col my-2">
            <%= textarea f, :message, placeholder: "Message", class: "border-2 border-gray-700 rounded p-1 h-24" %>
            <%= custom_error_tag f, :message %>
        </p>
        <div class="flex mt-4">
            <p class="flex flex-col mr-4">
                <%= text_input f, :username, placeholder: "Username", class: "border-2 border-gray-700 rounded p-1" %>
                <%= custom_error_tag f, :username %>
            </p>
            <%= submit "Send", class: "bg-gray-300 hover:bg-gray-400 border-2 border-black rounded-md w-24 ml-2 mb-4 mt-0 h-8" %>
        </div>
    <% end %>
</section>