lib/forum_web/router.ex
defmodule ForumWeb.Router do
  use ForumWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ForumWeb do
    pipe_through :browser

    get "/", ThreadController, :index
    get "/thread/new", ThreadController, :new

    resources "/thread", ThreadController, only: [:show, :create, :delete] do
      resources "/", CommentController, only: [:create, :delete]
    end
  end

  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ForumWeb.Telemetry
    end
  end
end

lib/forum_web/views/layout_view.ex
defmodule ForumWeb.LayoutView do
  use ForumWeb, :view
end

lib/forum_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Forum</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/main.css") %>"/>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>

  </head>
  <body>
    <main role="main" class="px-96 mt-8 flex flex-col justify-center">
      <header class="mb-8 relative">
        <%= if get_flash(@conn, :info) do%>
          <p class="bg-blue-100 border-2 border-blue-300 text-blue-900 text-center w-1/3 rounded-md px-2 py-2 absolute top-2 right-0" role="alert"><%= get_flash(@conn, :info) %></p>
        <% end %>
        <%= if get_flash(@conn, :error) do%>
          <p class="bg-red-100 border-2 border-red-300 text-red-500 text-center w-1/3 rounded-md px-2 py-2 absolute top-2 right-0" role="alert"><%= get_flash(@conn, :error) %></p>
        <% end %>
        <%= if assigns[:show_thread_list_button] || false do%>
          <%= link "< Back to threads list", to: Routes.thread_path(@conn, :index),
          class: "bg-gray-300 hover:bg-gray-400 border-2 border-black rounded-md px-1
          h-8 text-center pt-0.5 absolute top-2 left-0", method: :get %>
        <% end %>
        <p><h1 class="text-6xl text-center">Forum</h1></p>
      </header>
      <%= @inner_content %>
    </main>
  </body>
</html>